import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Define styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 15,
  },
  brand: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#6366f1',
    marginBottom: 15,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#334155',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    paddingBottom: 5,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  label: {
    width: 120,
    fontSize: 12,
    color: '#64748b',
    fontWeight: 'bold',
  },
  value: {
    fontSize: 12,
    color: '#0f172a',
  },
  scoreBox: {
    backgroundColor: '#f8fafc',
    padding: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  overallScoreText: {
    fontSize: 14,
    color: '#64748b',
    marginBottom: 5,
  },
  overallScoreValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#6366f1',
  },
  metricsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  metricCard: {
    width: '30%',
    backgroundColor: '#f8fafc',
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  metricLabel: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 5,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 8,
  },
  barBg: {
    height: 6,
    backgroundColor: '#e2e8f0',
    borderRadius: 3,
  },
  barFillPurple: { height: 6, backgroundColor: '#8b5cf6', borderRadius: 3 },
  barFillBlue: { height: 6, backgroundColor: '#3b82f6', borderRadius: 3 },
  barFillGreen: { height: 6, backgroundColor: '#22c55e', borderRadius: 3 },
  
  bulletItem: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  bulletPoint: {
    width: 10,
    fontSize: 12,
    color: '#64748b',
  },
  bulletText: {
    flex: 1,
    fontSize: 11,
    color: '#334155',
    lineHeight: 1.4,
  },
  qCard: {
    marginBottom: 15,
    padding: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  qHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  qTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0f172a',
    flex: 1,
  },
  qScore: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#3b82f6',
    marginLeft: 10,
  },
  qNote: {
    fontSize: 11,
    color: '#475569',
    lineHeight: 1.4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 10,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 10,
  },
});

export const ReportPDFDocument = ({ report, interview, candidateName, date }) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>INTERACT.AI</Text>
          <Text style={styles.title}>AI INTERVIEW PERFORMANCE REPORT</Text>
          <Text style={styles.subtitle}>Generated by Interact Gemini AI Interview Engine</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>Candidate:</Text>
            <Text style={styles.value}>{candidateName || 'Candidate'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Role:</Text>
            <Text style={styles.value}>{interview?.target_role || 'Software Engineer'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Domain:</Text>
            <Text style={styles.value}>{interview?.domain || 'Technical'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date:</Text>
            <Text style={styles.value}>{date || new Date().toLocaleDateString()}</Text>
          </View>
        </View>

        <View style={styles.scoreBox}>
          <Text style={styles.overallScoreText}>OVERALL SCORE</Text>
          <Text style={styles.overallScoreValue}>{report?.overallScore || 0} / 100</Text>
        </View>

        <View style={styles.metricsGrid}>
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Technical Knowledge</Text>
            <Text style={styles.metricValue}>{report?.technicalKnowledge || 0}%</Text>
            <View style={styles.barBg}>
              <View style={[styles.barFillPurple, { width: `${report?.technicalKnowledge || 0}%` }]} />
            </View>
          </View>
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Communication</Text>
            <Text style={styles.metricValue}>{report?.communication || 0}%</Text>
            <View style={styles.barBg}>
              <View style={[styles.barFillBlue, { width: `${report?.communication || 0}%` }]} />
            </View>
          </View>
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Problem Solving</Text>
            <Text style={styles.metricValue}>{report?.problemSolving || 0}%</Text>
            <View style={styles.barBg}>
              <View style={[styles.barFillGreen, { width: `${report?.problemSolving || 0}%` }]} />
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>PERFORMANCE ANALYSIS</Text>
          
          <Text style={[styles.label, { marginBottom: 5, color: '#16a34a' }]}>Strengths</Text>
          {report?.strengths?.map((s, idx) => (
            <View style={styles.bulletItem} key={`s-${idx}`}>
              <Text style={styles.bulletPoint}>•</Text>
              <Text style={styles.bulletText}>{s}</Text>
            </View>
          ))}

          <Text style={[styles.label, { marginTop: 10, marginBottom: 5, color: '#ea580c' }]}>Areas to Improve</Text>
          {report?.weaknesses?.map((w, idx) => (
            <View style={styles.bulletItem} key={`w-${idx}`}>
              <Text style={styles.bulletPoint}>•</Text>
              <Text style={styles.bulletText}>{w}</Text>
            </View>
          ))}
          
          <Text style={[styles.label, { marginTop: 10, marginBottom: 5, color: '#7c3aed' }]}>Recommended Study Plan</Text>
          <View style={styles.bulletItem}>
            <Text style={styles.bulletPoint}>•</Text>
            <Text style={styles.bulletText}>{report?.recommendedPractice}</Text>
          </View>
        </View>

        <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
          `Interact.ai - AI-powered interview assessment • Page ${pageNumber} of ${totalPages}`
        )} fixed />
      </Page>

      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>INTERACT.AI</Text>
          <Text style={styles.title}>QUESTION ANALYSIS</Text>
        </View>

        <View style={styles.section}>
          {report?.questionFeedback?.map((item, idx) => (
            <View style={styles.qCard} key={`q-${idx}`} wrap={false}>
              <View style={styles.qHeader}>
                <Text style={styles.qTitle}>Q{idx + 1}: {item.q}</Text>
                <Text style={styles.qScore}>Score: {item.score}/100</Text>
              </View>
              <Text style={styles.qNote}>{item.note}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
          `Interact.ai - AI-powered interview assessment • Page ${pageNumber} of ${totalPages}`
        )} fixed />
      </Page>
    </Document>
  );
};
